//Admin Login
export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'

//Store Request
export const ADMIN_STORE_REQUEST_REQUEST = 'ADMIN_STORE_REQUEST_REQUEST'
export const ADMIN_STORE_REQUEST_SUCCESS = 'ADMIN_STORE_REQUEST_SUCCESS'
export const ADMIN_STORE_REQUEST_FAIL = 'ADMIN_STORE_REQUEST_FAIL'

//Specific Store Request
export const ADMIN_SPECIFIC_STORE_REQUEST = 'ADMIN_SPECIFIC_STORE_REQUEST'
export const ADMIN_SPECIFIC_STORE_SUCCESS = 'ADMIN_SPECIFIC_STORE_SUCCESS'
export const ADMIN_SPECIFIC_STORE_FAIL = 'ADMIN_SPECIFIC_STORE_FAIL'

//Approve Store Owner
export const ADMIN_APPROVE_STORE_REQUEST = 'ADMIN_APPROVE_STORE_REQUEST'
export const ADMIN_APPROVE_STORE_SUCCESS = 'ADMIN_APPROVE_STORE_SUCCESS'
export const ADMIN_APPROVE_STORE_FAIL = 'ADMIN_APPROVE_STORE_FAIL'

//Approve Store Owner
export const ADMIN_BLOCK_UNBLOCK_STORE_REQUEST = 'ADMIN_BLOCK_UNBLOCK_STORE_REQUEST'
export const ADMIN_BLOCK_UNBLOCK_STORE_SUCCESS = 'ADMIN_BLOCK_UNBLOCK_STORE_SUCCESS'
export const ADMIN_BLOCK_UNBLOCK_STORE_FAIL = 'ADMIN_BLOCK_UNBLOCK_STORE_FAIL'

//Approve Store Owner
export const ADMIN_DELETE_STORE_REQUEST = 'ADMIN_DELETE_STORE_REQUEST'
export const ADMIN_DELETE_STORE_SUCCESS = 'ADMIN_DELETE_STORE_SUCCESS'
export const ADMIN_DELETE_STORE_FAIL = 'ADMIN_DELETE_STORE_FAIL'

//Store List
export const ADMIN_STORE_LIST_REQUEST = 'ADMIN_STORE_LIST_REQUEST'
export const ADMIN_STORE_LIST_SUCCESS = 'ADMIN_STORE_LIST_SUCCESS'
export const ADMIN_STORE_LIST_FAIL = 'ADMIN_STORE_LIST_FAIL'

//Specific Store List
export const ADMIN_SPECIFIC_STORE_LIST_REQUEST = 'ADMIN_SPECIFIC_STORE_LIST_REQUEST'
export const ADMIN_SPECIFIC_STORE_LIST_SUCCESS = 'ADMIN_SPECIFIC_STORE_LIST_SUCCESS'
export const ADMIN_SPECIFIC_STORE_LIST_FAIL = 'ADMIN_SPECIFIC_STORE_LIST_FAIL'