//Add Order
export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

//Fetch Orders
export const FETCH_ORDERS_REQUEST = "FETCH_ORDERS_REQUEST";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

//Fetch Orders
export const FETCH_ORDER_REQUEST = "FETCH_ORDER_REQUEST";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAIL = "FETCH_ORDER_FAIL";

//Approve Orders
export const APPROVE_ORDER_REQUEST = "APPROVE_ORDER_REQUEST";
export const APPROVE_ORDER_SUCCESS = "APPROVE_ORDER_SUCCESS";
export const APPROVE_ORDER_FAIL = "APPROVE_ORDER_FAIL";

//Approve Orders
export const CANCEL_ORDER_REQUEST = "CANCEL_ORDER_REQUEST";
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS";
export const CANCEL_ORDER_FAIL = "CANCEL_ORDER_FAIL";

//Approve Orders
export const COMPLETE_ORDER_REQUEST = "COMPLETE_ORDER_REQUEST";
export const COMPLETE_ORDER_SUCCESS = "COMPLETE_ORDER_SUCCESS";
export const COMPLETE_ORDER_FAIL = "COMPLETE_ORDER_FAIL";

//Fetch User Orders
export const FETCH_USER_ORDERS_REQUEST = "FETCH_USER_ORDERS_REQUEST";
export const FETCH_USER_ORDERS_SUCCESS = "FETCH_USER_ORDERS_SUCCESS";
export const FETCH_USER_ORDERS_FAIL = "FETCH_USER_ORDERS_FAIL";

//Fetch User Orders
export const FETCH_SPECIFIC_STORE_ORDERS_REQUEST = "FETCH_SPECIFIC_STORE_ORDERS_REQUEST";
export const FETCH_SPECIFIC_STORE_ORDERS_SUCCESS = "FETCH_SPECIFIC_STORE_ORDERS_SUCCESS";
export const FETCH_SPECIFIC_STORE_ORDERS_FAIL = "FETCH_SPECIFIC_STORE_ORDERS_FAIL";