//Add Order
export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

//Fetch Orders
export const FETCH_ORDERS_REQUEST = "FETCH_ORDERS_REQUEST";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

//Fetch Orders
export const FETCH_ORDER_REQUEST = "FETCH_ORDER_REQUEST";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAIL = "FETCH_ORDER_FAIL";

//Approve Orders
export const APPROVE_ORDER_REQUEST = "APPROVE_ORDER_REQUEST";
export const APPROVE_ORDER_SUCCESS = "APPROVE_ORDER_SUCCESS";
export const APPROVE_ORDER_FAIL = "APPROVE_ORDER_FAIL";

//Cancel Orders
export const CANCEL_ORDER_REQUEST = "CANCEL_ORDER_REQUEST";
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS";
export const CANCEL_ORDER_FAIL = "CANCEL_ORDER_FAIL";

//Complete Orders
export const COMPLETE_ORDER_REQUEST = "COMPLETE_ORDER_REQUEST";
export const COMPLETE_ORDER_SUCCESS = "COMPLETE_ORDER_SUCCESS";
export const COMPLETE_ORDER_FAIL = "COMPLETE_ORDER_FAIL";

//Fetch User Orders
export const FETCH_USER_ORDERS_REQUEST = "FETCH_USER_ORDERS_REQUEST";
export const FETCH_USER_ORDERS_SUCCESS = "FETCH_USER_ORDERS_SUCCESS";
export const FETCH_USER_ORDERS_FAIL = "FETCH_USER_ORDERS_FAIL";

//Fetch User Orders
export const FETCH_SPECIFIC_STORE_ORDERS_REQUEST = "FETCH_SPECIFIC_STORE_ORDERS_REQUEST";
export const FETCH_SPECIFIC_STORE_ORDERS_SUCCESS = "FETCH_SPECIFIC_STORE_ORDERS_SUCCESS";
export const FETCH_SPECIFIC_STORE_ORDERS_FAIL = "FETCH_SPECIFIC_STORE_ORDERS_FAIL";

//Printing press orders
export const PRINTING_PRESS_ORDER_FAIL = 'PRINTING_PRESS_ORDER_FAIL'
export const PRINTING_PRESS_ORDER_SUCCESS = 'PRINTING_PRESS_ORDER_SUCCESS'
export const PRINTING_PRESS_ORDER_REQUEST = 'PRINTING_PRESS_ORDER_REQUEST'

//Add Printing Order
export const PRINTING_ORDER_CREATE_REQUEST = "PRINTING_ORDER_CREATE_REQUEST";
export const PRINTING_ORDER_CREATE_SUCCESS = "PRINTING_ORDER_CREATE_SUCCESS";
export const PRINTING_ORDER_CREATE_FAIL = "PRINTING_ORDER_CREATE_FAIL";
export const PRINTING_ORDER_CREATE_RESET = "PRINTING_ORDER_CREATE_RESET";

//Fetch Printing Orders
export const FETCH_PRINTING_ORDERS_REQUEST = "FETCH_PRINTING_ORDERS_REQUEST";
export const FETCH_PRINTING_ORDERS_SUCCESS = "FETCH_PRINTING_ORDERS_SUCCESS";
export const FETCH_PRINTING_ORDERS_FAIL = "FETCH_PRINTING_ORDERS_FAIL";

//Fetch Printing Orders
export const FETCH_PRINTING_ORDER_REQUEST = "FETCH_PRINTING_ORDER_REQUEST";
export const FETCH_PRINTING_ORDER_SUCCESS = "FETCH_PRINTING_ORDER_SUCCESS";
export const FETCH_PRINTING_ORDER_FAIL = "FETCH_PRINTING_ORDER_FAIL";

//Approve Printing Orders
export const APPROVE_PRINTING_ORDER_REQUEST = "APPROVE_PRINTING_ORDER_REQUEST";
export const APPROVE_PRINTING_ORDER_SUCCESS = "APPROVE_PRINTING_ORDER_SUCCESS";
export const APPROVE_PRINTING_ORDER_FAIL = "APPROVE_PRINTING_ORDER_FAIL";

//Cancel Printing Orders
export const CANCEL_PRINTING_ORDER_REQUEST = "CANCEL_PRINTING_ORDER_REQUEST";
export const CANCEL_PRINTING_ORDER_SUCCESS = "CANCEL_PRINTING_ORDER_SUCCESS";
export const CANCEL_PRINTING_ORDER_FAIL = "CANCEL_PRINTING_ORDER_FAIL";

//Complete Printing Orders
export const COMPLETE_PRINTING_ORDER_REQUEST = "COMPLETE_PRINTING_ORDER_REQUEST";
export const COMPLETE_PRINTING_ORDER_SUCCESS = "COMPLETE_PRINTING_ORDER_SUCCESS";
export const COMPLETE_PRINTING_ORDER_FAIL = "COMPLETE_PRINTING_ORDER_FAIL";