//Create Store
export const CREATE_STORE_REQUEST = "CREATE_STORE_REQUEST";
export const CREATE_STORE_SUCCESS = "CREATE_STORE_SUCCESS";
export const CREATE_STORE_FAIL = "CREATE_STORE_FAIL";

//Create Store
export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";

//Fetch Stpre
export const FETCH_STORE_REQUEST = "FETCH_STORE_REQUEST";
export const FETCH_STORE_SUCCESS = "FETCH_STORE_SUCCESS";
export const FETCH_STORE_FAIL = "FETCH_STORE_FAIL";

//Fetch Stpre
export const FETCH_USER_STORE_REQUEST = "FETCH_USER_STORE_REQUEST";
export const FETCH_USER_STORE_SUCCESS = "FETCH_USER_STORE_SUCCESS";
export const FETCH_USER_STORE_FAIL = "FETCH_USER_STORE_FAIL";

//Fetch Stpre
export const FETCH_STORES_REQUEST = "FETCH_STORES_REQUEST";
export const FETCH_STORES_SUCCESS = "FETCH_STORES_SUCCESS";
export const FETCH_STORES_FAIL = "FETCH_STORES_FAIL";

//Update Store
export const UPDATE_STORE_REQUEST = "UPDATE_STORE_REQUEST";
export const UPDATE_STORE_SUCCESS = "UPDATE_STORE_SUCCESS";
export const UPDATE_STORE_FAIL = "UPDATE_STORE_FAIL";

//Fetch Products
export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";

//Fetch Products
export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAIL = "FETCH_PRODUCT_FAIL";

//Update product
export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAIL = "EDIT_PRODUCT_FAIL";

//Delete product
export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

//Create Review 
export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";

//Store Review 
export const STORE_REVIEWED_REQUEST = "STORE_REVIEWED_REQUEST";
export const STORE_REVIEWED_SUCCESS = "STORE_REVIEWED_SUCCESS";
export const STORE_REVIEWED_FAIL = "STORE_REVIEWED_FAIL";

//Fetch Stpre
export const FETCH_PRINTING_PRESS_REQUEST = "FETCH_PRINTING_PRESS_REQUEST";
export const FETCH_PRINTING_PRESS_SUCCESS = "FETCH_PRINTING_PRESS_SUCCESS";
export const FETCH_PRINTING_PRESS_FAIL = "FETCH_PRINTING_PRESS_FAIL";
